# Generated by Django 3.2.15 on 2022-08-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_CR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.CharField(db_column='train_no', max_length=200)),
            ],
            options={
                'db_table': 'main_CR',
                'managed': False,
            },
        ),
    ]
